<?php
/*

sforms module by Dharmendra Patri

This is a custom module.

*/

include dirname(__FILE__).'/db_helper.php';
include dirname(__FILE__).'/includes.inc';

function sforms_theme() 
{
  return array(
    'show_registered_complaints' => array(
      'arguments' => array('dept_options' => NULL,'city_dropdown'=>NULL,'msg' => NULL),
      'template' => 'view/complaint-form',
      'file' => 'sforms.inc')
	, 
    'search' => array(
      'arguments' => array('msg' => NULL),
      'template' => 'view/search',
      'file' => 'sforms.inc')		
	, 
    'i_dint_pay_a_bribe' => array(
      'arguments' => array('dept_options' => NULL,'city_dropdown'=>NULL, 'msg' => NULL),
      'template' => 'view/dint-pay-bribe-form',
      'file' => 'sforms.inc')
	,
	 'delete_names' => array(
      'arguments' => array('name'=> NULL ,'result'=>NULL),
      'template' => 'view/admin/delete-names',
      'file' => 'admin.sforms.inc')
	  ,	
    'i_dint_have_to_pay_a_bribe' => array(
      'arguments' => array('dept_options' => NULL,'city_dropdown'=>NULL, 'msg' => NULL),
      'template' => 'view/dint-have-to-pay-bribe-form',
      'file' => 'sforms.inc')
    , 	
	'view_reports_paid' => array(
      'arguments' => array('result' => NULL,'dept_options'=>NULL,'city_dropdown'=>NULL,'num_recs'=>NULL),
      'template' => 'view/view-reports-paid',
      'file' => 'sforms.inc')
	, 
	'view_reports_dint_pay' => array(
      'arguments' => array('result' => NULL,'dept_options'=>NULL,'city_dropdown'=>NULL,'num_recs'=>NULL),
      'template' => 'view/view-reports-dint-pay',
      'file' => 'sforms.inc')
	,	
	'view_reports_dint_have_to_pay' => array(
      'arguments' => array('result' => NULL,'dept_options'=>NULL,'city_dropdown'=>NULL,'num_recs'=>NULL),
      'template' => 'view/view-reports-dint-have-to-pay',
      'file' => 'sforms.inc')	
	,
	  'ask_raghu' => array(
      'arguments' => array('dept_options' => NULL,'msg'=> NULL),
      'template' => 'view/ask-raghu-form',
      'file' => 'sforms.inc')
	 ,
	  'sign_pledge' => array(
      'arguments' => array('number_of_people_signed' => NULL,'msg' => NULL),
      'template' => 'view/sign-pledge',
      'file' => 'sforms.inc')
	 ,
	  'register_for_updates' => array(
      'arguments' => array('number_of_people_signed' => NULL,'msg' => NULL),
      'template' => 'view/register-for-updates',
      'file' => 'sforms.inc')
	 ,	 
	  'view_raghu_answers' => array(
      'arguments' => array('result'=>NULL, 'dept_options' => NULL,'num_recs'=> NULL),
      'template' => 'view/view-raghu-answers',
      'file' => 'sforms.inc')
	 ,
	 'corruption_commons' => array(
      'arguments' => array('result'=>NULL, 'dept_options' => NULL,'msg'=> NULL),
      'template' => 'view/corruption-commons',
      'file' => 'sforms.inc')	 
	 ,
	 'view_comments_paid' => array(
      'arguments' => array('row_det'=>NULL, 'res_com' => NULL,'msg'=> NULL),
      'template' => 'view/view-comments-paid',
      'file' => 'sforms.inc')	 	 
	 ,
	 'view_comments_dint_pay' => array(
      'arguments' => array('row_det'=>NULL, 'res_com' => NULL,'msg'=> NULL),
      'template' => 'view/view-comments-dint-pay',
      'file' => 'sforms.inc')	 	 
	 ,
	 'view_comments_dint_have_to_pay' => array(
      'arguments' => array('row_det'=>NULL, 'res_com' => NULL,'msg'=> NULL),
      'template' => 'view/view-comments-dint-have-to-pay',
      'file' => 'sforms.inc')	 	 
	 ,	 
	 'view_comments_raghu_answers' => array(
      'arguments' => array('row_det'=>NULL, 'res_com' => NULL,'msg'=> NULL),
      'template' => 'view/view-comments-raghu-answers',
      'file' => 'sforms.inc')	 	 	 
	 ,
	 'view_vote_comments' => array(
      'arguments' => array('res_com' => NULL,'msg'=> NULL),
      'template' => 'view/view-vote-comments',
      'file' => 'sforms.inc')	 	 
	 ,
	 'add_comment_form' => array(
      'arguments' => array('msg'=> NULL),
      'template' => 'view/add-comment-form',
      'file' => 'sforms.inc')	
      ,
	 'add_video' => array(
      'arguments' => array('msg'=> NULL),
      'template' => 'view/add-video',
      'file' => 'sforms.inc')	 	 
	 	,
	  'view_paid_bribes' => array(
      'arguments' => array('result'=>NULL, 'dept_options'=>NULL, 'msg'=> NULL),
      'template' => 'view/admin/view-paid-bribes',
      'file' => 'admin.sforms.inc') 
	 ,
	 'get_update_emails' => array(
      'arguments' => array('result'=>NULL, 'dept_options'=>NULL, 'msg'=> NULL),
      'template' => 'view/admin/get_update_emails',
      'file' => 'admin.sforms.inc') 
	 ,		 
	  'view_detail_paid_bribes' => array(
      'arguments' => array('result'=>NULL, 'msg'=> NULL),
      'template' => 'view/admin/view-detail-paid-bribes',
      'file' => 'admin.sforms.inc') 
	  ,
	  'view_not_paid_bribes' => array(
      'arguments' => array('result'=>NULL, 'dept_options'=>NULL,'msg'=> NULL),
      'template' => 'view/admin/view-not-paid-bribes',
      'file' => 'admin.sforms.inc')
	  ,
	  'add_names' => array(
      'arguments' => array('name'=> NULL ,'result'=>NULL),
      'template' => 'view/admin/add-names',
      'file' => 'admin.sforms.inc')
	  ,
	  'view_dint_have_to_pay' => array(
      'arguments' => array('result'=>NULL, 'dept_options'=>NULL,'msg'=> NULL),
      'template' => 'view/admin/view-dint-have-to-pay',
      'file' => 'admin.sforms.inc')	  
	  ,
	  'view_detail_not_paid_bribes' => array(
      'arguments' => array('result'=>NULL, 'msg'=> NULL),
      'template' => 'view/admin/view-detail-not-paid-bribes',
      'file' => 'admin.sforms.inc')
	  ,
	  'view_detail_dint_have_to_pay' => array(
      'arguments' => array('result'=>NULL, 'msg'=> NULL),
      'template' => 'view/admin/view-detail-dint-have-to-pay',
      'file' => 'admin.sforms.inc')	  
	  ,
      'edit_bribe' => array(
      'arguments' => array('result'=>NULL, 'msg'=> NULL),
      'template' => 'view/admin/view-edit-details',
      'file' => 'admin.sforms.inc')      
      ,
	  'ask_raghu_list' => array(
      'arguments' => array('result'=>NULL, 'dept_options'=>NULL,'num_recs'=>NULL,'msg'=> NULL),
      'template' => 'view/admin/ask-raghu-list',
      'file' => 'admin.sforms.inc')
	  ,
	  'poll_answer' => array(
      'arguments' => array('poll_details' => NULL, 'poll_questions' => NULL , 'msg' => NULL),
      'template' => 'view/poll-answer',
      'file' => 'sforms.inc')	  
	  ,
	'albums' => array(
      'arguments' => array('thumbs' => NULL,'images' => NULL,'albumTitle' => NULL),
      'template' => 'view/albums',
      'file' => 'sforms.inc')	  
	  ,
	  'ask_raghu_detail' => array(
      'arguments' => array('result'=>NULL, 'dept_options'=>NULL,'msg'=> NULL),
      'template' => 'view/admin/ask-raghu-detail',
      'file' => 'admin.sforms.inc')	   

    );
    
}

function sforms_help($path, $arg) 
{
  $output = '';  //declare your output variable
  switch ($path) 
  {
    case "admin/help#sforms":
      $output = '<p>'.  t("Will show register complaint form in the front end.") .'</p>';
      break;
  }
  return $output;
} // function


function sforms_perm()
{
	return array('access sforms content', 'administer sforms');
}

/**
 * Implementation of hook_menu().
 */
function sforms_menu()
{
  $items = array();
  
  /*Admin Menu*/
  $items['admin/sforms'] = array(
    'title' => 'Bribe Management',
    'description' => 'Bribe Management',
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
	);
  
  $items['admin/sforms/view_paid_bribes'] = array(
    'title' => 'Paid Bribe List',
    'description' => 'Paid Bribe List',
    'page callback' => 'view_paid_bribes',
    'access arguments' => array('administer sforms'),
    'file' => 'admin.sforms.inc',
  );
  
  $items['admin/sforms/get_update_emails'] = array(
    'title' => 'Get User List',
    'description' => 'Get User List',
    'page callback' => 'get_update_emails',
    'access arguments' => array('administer sforms'),
    'file' => 'admin.sforms.inc',
  );
  
  $items['admin/sforms/view_detail_paid_bribes'] = array(
    'title' => 'Detail Paid Bribe',
    'description' => 'Detail Paid Bribe',
    'page callback' => 'view_detail_paid_bribes',
    'access arguments' => array('administer sforms'),
	'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );
  
  $items['admin/sforms/view_not_paid_bribes'] = array(
    'title' => 'Didn\'t Pay Bribe List',
    'description' => 'Didn\'t Pay Bribe List',
    'page callback' => 'view_not_paid_bribes',
    'access arguments' => array('administer sforms'),
    'file' => 'admin.sforms.inc',
  );
  
  $items['admin/sforms/view_dint_have_to_pay'] = array(
    'title' => 'Didn\'t Have to Pay Bribe',
    'description' => 'List of Didnot Have to Pay a Bribe Users',
    'page callback' => 'view_dint_have_to_pay',
    'access arguments' => array('administer sforms'),
    'file' => 'admin.sforms.inc',
  );    
    $items['admin/sforms/add_names'] = array(
    'title' => 'Add Names',
    'description' => 'List of Names',
    'page callback' => 'add_names',
    'access arguments' => array('administer sforms'),
    'file' => 'admin.sforms.inc',
  );    

    $items['admin/sforms/delete_names'] = array(
    'title' => 'Delete Names',
    'description' => 'Deletion Names',
    'page callback' => 'delete_names',
    'access arguments' => array('administer sforms'),
    'file' => 'admin.sforms.inc',
  );    

  $items['admin/sforms/view_detail_not_paid_bribes'] = array(
    'title' => 'Detail Paid Bribe',
    'description' => 'Detail Paid Bribe',
    'page callback' => 'view_detail_not_paid_bribes',
    'access arguments' => array('administer sforms'),
	'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );

  $items['admin/sforms/view_detail_dint_have_to_pay'] = array(
    'title' => 'Detail Didnot have to pay bribe',
    'description' => 'Detail Didnot have to pay bribe',
    'page callback' => 'view_detail_dint_have_to_pay',
    'access arguments' => array('administer sforms'),
	'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );

   $items['admin/sforms/delete_bribe'] = array(
    'page callback' => 'delete_bribe',
    'access arguments' => array('administer sforms'),
	'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );
  
    $items['admin/sforms/update_bribe'] = array(
    'page callback' => 'update_bribe',
    'access arguments' => array('administer sforms'),
    'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );
  
  $items['admin/sforms/edit_bribe'] = array(
    'title' => 'Edit Bribe Details',
    'description' => 'Edit Details',
    'page callback' => 'edit_bribe',
    'access arguments' => array('administer sforms'),
    'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );
   
   $items['admin/sforms/publish_unpublish'] = array(
    'page callback' => 'publish_unpublish',
    'access arguments' => array('administer sforms'),
	'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );   
  
   $items['admin/sforms/ask_raghu_list'] = array(
    'title' => 'Ask Raghu List',
    'description' => 'Ask Raghu List',
    'page callback' => 'ask_raghu_list',
    'access arguments' => array('administer sforms'),
    'file' => 'admin.sforms.inc',
  );
   
   $items['admin/sforms/ask_raghu_detail'] = array(
    'title' => 'Ask Raghu Detail',
    'description' => 'Ask Raghu Detail',
    'page callback' => 'ask_raghu_detail',
    'access arguments' => array('administer sforms'),
	'type' => MENU_CALLBACK,
    'file' => 'admin.sforms.inc',
  );
   
   /*front end menus*/
   $items['sforms/register/complaints'] = array(
    'title' => 'Registered Complaints List',
    'description' => 'Registered Complaints List',
    'page callback' => 'show_registered_complaints',
	'access arguments' => array('access sforms content'),
	'type' => MENU_CALLBACK,
    'file' => 'sforms.inc',
  );     
         
   $items['sforms/register/i_didnt_pay_a_bribe'] = array(
    'title' => 'I did not pay a bribe',
    'description' => 'I did not pay a bribe',
    'page callback' => 'i_dint_pay_a_bribe',
	'access arguments' => array('access sforms content'),
	'type' => MENU_CALLBACK,
    'file' => 'sforms.inc',
  );
   
   $items['sforms/get_transactions'] = array(
    'page callback' => 'transactions_dropdown',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
 
   $items['sforms/albums'] = array(
    'page callback' => 'albums',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
   $items['sforms/view_reports_paid'] = array(
    'page callback' => 'view_reports_paid',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
	
   $items['sforms/sign_pledge'] = array(
    'page callback' => 'sign_pledge',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
   $items['sforms/register_for_updates'] = array(
    'page callback' => 'register_for_updates',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );	  
   
   $items['sforms/view_reports_didnt_pay'] = array(
    'page callback' => 'view_reports_dint_pay',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
   
   $items['sforms/get_spam_image'] = array(
    'page callback' => 'show_captcha',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
   
   $items['sforms/ask_raghu'] = array(
    'page callback' => 'ask_raghu',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
   
   $items['sforms/view_raghu_answers'] = array(
    'page callback' => 'view_raghu_answers',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
   
  $items['sforms/hot_topics'] = array(
    'page callback' => 'hot_topics',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );

  $items['sforms/ipab_impact'] = array(
    'page callback' => 'ipab_impact',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );


  $items['sforms/ipab_in_the_press'] = array(
    'page callback' => 'press',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/on_your_case'] = array(
    'page callback' => 'on_your_case',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/on_air'] = array(
    'page callback' => 'on_air',
	'page arguments' => array(1),
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/govt_promises'] = array(
    'page callback' => 'govt_promises',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
	  
  $items['sforms/we_have_got_news'] = array(
    'page callback' => 'we_have_got_news',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/view_reports_didnt_have_to_pay'] = array(
    'page callback' => 'view_reports_dint_have_to_pay',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );  
  
   $items['sforms/poll_answer'] = array(
    'page callback' => 'poll_answer',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
   
	$items['sforms/corruption_commons'] = array(
    'page callback' => 'corruption_commons',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/view_comments_paid'] = array(
    'page callback' => 'view_comments_paid',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/view_report_paid'] = array(
    'page callback' => 'view_comments_paid',
    'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );

  $items['sforms/view_comments_didnt_pay'] = array(
    'page callback' => 'view_comments_dint_pay',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/view_report_didnt_pay'] = array(
    'page callback' => 'view_comments_dint_pay',
    'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/view_comments_didnt_have_to_pay'] = array(
    'page callback' => 'view_comments_dint_have_to_pay',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/view_report_didnt_have_to_pay'] = array(
    'page callback' => 'view_comments_dint_have_to_pay',
    'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/view_comments_raghu_answers'] = array(
    'page callback' => 'view_comments_raghu_answers',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/add_comment'] = array(
    'page callback' => 'add_comment',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/search'] = array(
    'page callback' => 'search',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
 
   $items['sforms/add_video'] = array(
    'page callback' => 'add_video',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
  
  $items['sforms/register/i_didnt_have_to_pay_a_bribe'] = array(
    'title' => 'I did not have to pay a bribe',
    'description' => 'I did not have to pay a bribe',
    'page callback' => 'i_dint_have_to_pay_a_bribe',
    'access arguments' => array('access sforms content'),
    'type' => MENU_CALLBACK,
    'file' => 'sforms.inc',
  );   
  
    $items['sforms/increment_count'] = array(
    'page callback' => 'increment_count',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  );
    
	$items['sforms/get_g_view_cnt'] = array(
    'page callback' => 'get_g_view_cnt',
	'access arguments' => array('access sforms content'),
    'file' => 'sforms.inc',
  ); 	 
  
  return $items;
}

//modify the array if required
function sforms_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
	return $node;
}
?>
