<?php
// $Id$ ulearn.info, v1.0 2010/17/14 12:52:23 Nanda Kishore Exp $
include dirname(__FILE__).'/db_helper.php';

/*******************************************************************************
************************* Hook Functions (Drupal) ******************************
*******************************************************************************/

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function ulearn_help ($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help/ulearn":
      $output = '<p>'.  t("This module is for an Online Learning Market Place for Students by Teachers.") .'</p>';
      break;
  }
  return $output;
} // function ulearn_help

/**
* Valid permissions for this module
* @return array An array of valid permissions for the onthisdate module
*/
function ulearn_perm() {
  return array('access student content', 'access teacher content', 'access both content');
} // function ulearn_perm()

/**
 * Menu for this module
 * @return array An array with this module's settings.
 */
function ulearn_menu() {
	
	$items = array();

	/*Admin Menu*/
	$items['admin/ulearn'] = array(
		'title' => 'ULearn Dashboard',
		'description' => 'ULearn - Online Learning Market Place',
		'page callback' => 'admin_ulearn_dashboard',
		'access arguments' => array('access administration pages'),
		'file' => 'admin.ulearn.inc',
	);
	
	$items['admin/ulearn/settings'] = array(
		'title' => 'Global Settings',
		'description' => 'ULearn Global Settings',
		'page callback' => 'admin_ulearn_settings',
		'access arguments' => array('access administration pages'),
		'file' => 'admin.ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['admin/ulearn/list'] = array(
		'title' => 'List Users',
		'description' => 'ULearn list users',
		'type' => MENU_CALLBACK,
		'page callback' => 'admin_ulearn_list',
		'access arguments' => array('access administration pages'),
		'file' => 'admin.ulearn.inc',
	);

	$items['admin/ulearn/transactions'] = array(
		'title' => 'Transactions History',
		'description' => 'All Transactions History',
		'page callback' => 'admin_ulearn_transactions',
		'access arguments' => array( 'access administration pages' ),
		'file' => 'admin.ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	//front end menus
	$items['dashboard'] = array(
		'title' => 'Dashboard',
		'description' => 'ULearn Dashboard Page',
		'page callback' => 'ulearn_dashboard',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
	);	

	$items['teachers'] = array(
		'title' => 'Teachers',
		'description' => 'Teachers',
		'page callback' => 'ulearn_list_teachers',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['view_package'] = array(
		'title' => 'Lesson Details',
		'description' => 'Lession Details',
		'page callback' => 'ulearn_view_package',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['remove_time'] = array(
		'title' => 'Remove Time',
		'description' => 'Remove time from the package',
		'page callback' => 'ulearn_remove_time',
		'access arguments' => array( 'access teacher content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['buy_package'] = array(
		'title' => 'Confirm Order',
		'description' => 'Confirm Order before proceed',
		'page callback' => 'ulearn_buy_package',
		'access arguments' => array( 'access student content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['proceed_payment'] = array(
		'title' => 'Insert Data',
		'description' => 'Insert data before going to paypal',
		'page callback' => 'ulearn_proceed_payment',
		'access arguments' => array( 'access student content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['success_payment'] = array(
		'title' => 'Payment Success',
		'description' => 'Payment successfully done...',
		'page callback' => 'ulearn_success_payment',
		'access arguments' => array( 'access student content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['cancel_payment'] = array(
		'title' => 'Payment Success',
		'description' => 'Payment Canceled',
		'page callback' => 'ulearn_cancel_payment',
		'access arguments' => array( 'access student content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['transactions'] = array(
		'title' => 'Transactions',
		'description' => 'Transactions History',
		'page callback' => 'ulearn_my_transactions',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);
	
	$items['registration_step2'] = array(
		'title' => 'Second Step',
		'description' => 'Teachers second step registration',
		'page callback' => 'ulearn_check_regstep2',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);
	
	$items['gotoregstep2'] = array(
		'title' => 'Second Step',
		'description' => 'Teachers second step registration',
		'page callback' => 'ulearn_gotoregstep2',
		'access arguments' => array( 'access teacher content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);
	
	$items['gotoregstep2'] = array(
		'title' => 'Second Step',
		'description' => 'Teachers second step registration',
		'page callback' => 'ulearn_gotoregstep2',
		'access arguments' => array( 'access teacher content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);
	
	$items['edit_package'] = array(
		'title' => 'Edit My Package Details',
		'description' => 'Edit My Package Details',
		'page callback' => 'ulearn_edit_package',
		'access arguments' => array( 'access teacher content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);
	
	$items['student_booking'] = array(
		'title' => 'Student Booking',
		'description' => 'Student Booking',
		'page callback' => 'ulearn_student_booking',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);
	
	$items['purchase_package'] = array(
		'title' => 'Selected Package',
		'description' => 'Your Selected Package Information',
		'page callback' => 'ulearn_purchase_package',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	$items['purchase_done'] = array(
		'title' => 'Congratulations!',
		'description' => 'Congratulations!',
		'page callback' => 'ulearn_purchase_done',
		'access arguments' => array( 'access both content' ),
		'file' => 'ulearn.inc',
		'type' => MENU_CALLBACK,
	);

	
	return $items;
}

/**
* Themes for this module
* Returns perticlar theme(view file)
*/
function ulearn_theme() {
	return array(
	
		/* Admin Theme */
		'admin_ulearn_dashboard' => array(
		'template' => 'view/admin/dashboard',
		'file' => 'admin.ulearn.inc'),

		'admin_ulearn_settings' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/admin/settings',
		'file' => 'admin.ulearn.inc'),

		'admin_ulearn_list' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/admin/list',
		'file' => 'admin.ulearn.inc'),

		'admin_ulearn_transactions' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/admin/transactions',
		'file' => 'admin.ulearn.inc'),

		/* Front end Theme */
		'ulearn_dashboard' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/dashboard',
		'file' => 'ulearn.inc'),
		
		'ulearn_list_teachers' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/list-teachers',
		'file' => 'ulearn.inc'),

		'ulearn_view_package' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/package',
		'file' => 'ulearn.inc'),

		'ulearn_buy_package' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/confirm',
		'file' => 'ulearn.inc'),

		'ulearn_my_transactions' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/transactions',
		'file' => 'ulearn.inc'),
		
		'ulearn_gotoregstep2' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/registration_step2',
		'file' => 'ulearn.inc'),	
		
		'ulearn_edit_package' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/edit_package',
		'file' => 'ulearn.inc'),	
		
		'ulearn_student_booking' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/student_booking',
		'file' => 'ulearn.inc'),
		
		'ulearn_purchase_package' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/confirm',
		'file' => 'ulearn.inc'),
	
		'ulearn_purchase_done' => array(
		'arguments' => array('result' => NULL, 'msg' => NULL),
		'template' => 'view/purchase_done',
		'file' => 'ulearn.inc'),
			
	);
}
?>
