<?php
/*

bribeart module by Dharmendra Patri

This is a custom module.

*/

function bribeart_theme()
{
	return array(
	'add_bribe_art' => array(
	'arguments' => array('msg' => NULL),
	'template' => 'view/add-bribe-art',
	'file' => 'bribeart.inc'),

	'view_bribe_arts' => array(
	'arguments' => array('result'=>NULL,'num_recs'=>NULL,'msg' => NULL),
	'template' => 'view/view-bribe-arts',
	'file' => 'bribeart.inc'),

	'full_view_bribe_art' => array(
	'arguments' => array('row'=>NULL,'res_comments'=>NULL,'next_page'=>NULL,'prev_page'=>NULL,'msg' => NULL),
	'template' => 'view/full-view-bribe-art',
	'file' => 'bribeart.inc'),

	'list_bribe_arts' => array(
	'arguments' => array('result'=>NULL,'num_recs'=>NULL,'msg' => NULL),
	'template' => 'view/admin/list-bribe-arts',
	'file' => 'admin.bribeart.inc'),
	);



}

function bribeart_help($path, $arg)
{
	$output = '';  //declare your output variable
	switch ($path)
	{
		case "admin/help#bribeart":
			$output = '<p>'.  t("Users can upload the pictures here and also can browse it, admin will be able to manage the uploaded pictures and added comments.") .'</p>';
			break;
	}
	return $output;
} // function


function bribeart_perm()
{
	return array('access bribeart content', 'administer bribeart');
}

/**
 * Implementation of hook_menu().
 */
function bribeart_menu()
{
	$items = array();

	/*Admin Menu*/
	$items['admin/bribeart'] = array(
	'title' => 'Bribe Art',
	'description' => 'Bribe Art',
	'position' => 'left',
	'page callback' => 'system_admin_menu_block_page',
	'access arguments' => array('access administration pages'),
	'file' => 'system.admin.inc',
	'file path' => drupal_get_path('module', 'system'),
	);

	$items['admin/bribeart/list_bribe_arts'] = array(
	'title' => 'View Bribe Arts',
	'description' => 'List of Added Arts',
	'page callback' => 'list_bribe_arts',
	'access arguments' => array('administer bribeart'),
	'file' => 'admin.bribeart.inc',
	);

	$items['admin/bribeart/publish_unpublish'] = array(
	'page callback' => 'publish_unpublish_art',
	'access arguments' => array('administer bribeart'),
	'type' => MENU_CALLBACK,
	'file' => 'admin.bribeart.inc',
	);

	$items['admin/bribeart/delete_art'] = array(
	'page callback' => 'delete_art',
	'access arguments' => array('administer bribeart'),
	'type' => MENU_CALLBACK,
	'file' => 'admin.bribeart.inc',
	);

	/*front end menus*/
	$items['bribeart/add_bribe_art'] = array(
	'title' => 'Upload a new bribe art',
	'description' => 'Upload a new bribe art',
	'page callback' => 'add_bribe_art',
	'access arguments' => array('access bribeart content'),
	'type' => MENU_CALLBACK,
	'file' => 'bribeart.inc',
	);

	$items['bribeart'] = array(
	'title' => 'View all added bribe arts in thumnbnails',
	'description' => 'View all added bribe arts in thumnbnails',
	'page callback' => 'view_bribe_arts',
	'access arguments' => array('access bribeart content'),
	'type' => MENU_CALLBACK,
	'file' => 'bribeart.inc',
	);

	$items['bribeart/view_bribe_arts'] = array(
	'title' => 'View all added bribe arts in thumnbnails',
	'description' => 'View all added bribe arts in thumnbnails',
	'page callback' => 'view_bribe_arts',
	'access arguments' => array('access bribeart content'),
	'type' => MENU_CALLBACK,
	'file' => 'bribeart.inc',
	);

	$items['bribeart/full_view_bribe_art'] = array(
	'title' => 'View a single bribe art',
	'description' => 'View a single bribe art',
	'page callback' => 'full_view_bribe_art',
	'access arguments' => array('access bribeart content'),
	'type' => MENU_CALLBACK,
	'file' => 'bribeart.inc',
	);

	$items['bribeart/add_bribe_art_comments'] = array(
	'title' => '',
	'description' => '',
	'page callback' => 'add_bribe_art_comments',
	'access arguments' => array('access bribeart content'),
	'type' => MENU_CALLBACK,
	'file' => 'bribeart.inc',
	);

	return $items;
}

?>
