<?php
// $Id$


/**
 * @file
 * Enable backup of a site archive with backup and migrate.
 */

/* Drupal Hooks */

/**
 * Implementation of hook_backup_migrate_destination_types().
 *
 * Get the built in Backup and Migrate file source type.
 */
function backup_migrate_archive_backup_migrate_destination_types() {
  $out = array();
  $out += array(
    'archive' => array(
      'description' => t('An archive of your entire site (backup source only).'),
      'file' => drupal_get_path('module', 'backup_migrate_archive') .'/includes/destinations.archivesource.inc',
      'class' => 'backup_migrate_files_destination_archivesource',
      'type_name' => t('Site Archive'),
      'can_create' => FALSE,
    ),
  );
  return $out;
}

